services:

  mongo:
    image: mongo
    container_name: ictusnet_mongo_production
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./database/mongodb:/data/db
    restart: always

  node:
    container_name: ictusnet_node_production
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    privileged: true
    environment:
      - MONGODB_HOST=mongo
    volumes:
      - /tmp/uploads:/tmp/uploads
      - /var/run/docker.sock:/var/run/docker.sock
    command: node app.js
    restart: always

  angular:
    container_name: ictusnet_angular_production
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 81:80
    restart: always
