version: "3.7"

services:
  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 9999:80

  express:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    command: node app.js
