services:

  mongo:
    image: mongo:4.4.5-bionic
    container_name: ictusnet_mongo
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./database/mongodb:/data/db

  node:
    container_name: ictusnet_node
    build: ./backend
    ports:
      - 3000:3000
    privileged: true
    env_file:
      - backend/paths.env
    environment:
      - BACKEND_ABSOLUTE_PATH_IN_HOST=/var/www/html/ictusnet-webapp/backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend:/app
    command: npm run dev

  angular:
    container_name: ictusnet_angular
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 81:4200
    command: npm run dev
