services:

  mongo:
    image: mongo:4.4.5-bionic
    container_name: ictusnet_mongo
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./database/mongodb:/data/db
    restart: always

  node:
    container_name: ictusnet_node
    build: ./backend
    ports:
      - 3000:3000
    privileged: true
    environment:
      - MONGODB_HOST=mongo
      - ICTUSNET_NER_DIR=/var/www/html/ictusnet-ner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/preannotations/brat:/app/preannotations/brat
      - /var/www/html/ictusnet-ner:/ictusnet-ner
    command: node src/app.js
    restart: always

  angular:
    container_name: ictusnet_angular
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 81:80
    restart: always
